# Generated by Django 4.0.3 on 2022-03-15 07:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='phone_number',
            field=models.CharField(default=1234567890, max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='/^(\\+\\d{1,3}[- ]?)?\\d{10}$/')]),
            preserve_default=False,
        ),
    ]
